description: 'ResNet CIFAR10'
output_dir: $SCRATCH/sc18-dl-tutorial/cifar10-resnet

data:
    name: cifar10

model:
    name: resnet18_cifar
    input_shape: [32, 32, 3]
    n_classes: 10
    dropout: 0.2

optimizer:
    name: Adam
    lr: 0.00001

training:
    batch_size: 32
    n_epochs: 16
    lr_warmup_epochs: 5
    loss: categorical_crossentropy
    metrics: [accuracy, top_k_categorical_accuracy]
