description: 'ResNet CIFAR10'
output_dir: $SCRATCH/sc18-dl-tutorial/cifar10-resnet

data:
    name: cifar10

model:
    name: resnet18_cifar
    input_shape: [32, 32, 3]
    n_classes: 10

optimizer:
    name: Adam
    lr: 0.0001

training:
    batch_size: 64
    n_epochs: 8
    lr_warmup_epochs: 5
    loss: categorical_crossentropy
    metrics: [accuracy]
