description: 'CNN CIFAR10'
output_dir: $SCRATCH/sc18-dl-tutorial/cifar10-cnn-N${SLURM_JOB_NUM_NODES}-${SLURM_JOB_ID}

data:
    name: cifar10

model:
    name: cnn
    input_shape: [32, 32, 3]
    n_classes: 10
    dropout: 0.2

optimizer:
    name: Adam
    lr: 0.001

training:
    batch_size: 64
    n_epochs: 64
    lr_warmup_epochs: 0
    loss: categorical_crossentropy
    metrics: [accuracy, top_k_categorical_accuracy]
